#/bin/bash

export MKL_THREADING_LAYER=GNU

X=`pwd`
Y=test_00

mode=initialize
initial_param=init_param   # initial parameters.
upside_input_dir=input     # the directory where upside input files can be found for all proteins in the training set. These are files generated by running PDB_to_initial_structure.py on the PDBs,
pdb_list=pdb_list      # a list containing the PDB ids of your training set

echo python condiv2.py $mode $initial_param $upside_input_dir $pdb_list $X/$Y
python condiv2.py $mode $initial_param $upside_input_dir $pdb_list $X/$Y | tee $X/$Y.output
